### ISSUE TITLE
Can you convert a .safetensors into a .pth?

### ISSUE THREAD

**Issue by foodornt** [Silver267/pytorch-to-safetensor-converter#2]
Title, is that possible?

**Comment by Silver267** [comment]
Correct me if I'm wrong, but I don't think pth files are used anywhere for llm inference?

**Comment by foodornt** [comment]
ah, I'm not sure about LLM, although I've seen some RVC models (the voice AI thingy) that were safetensors, although RVC software available on github is usually only compatible with .pth files

**Comment by Silver267** [comment]
This is out of scope of this program, it's only intended for converting LLMs, I'm sure there's other repos that can do this.
